language: rust
sudo: true

env:
    global:
        # Use in deploy
        - PROJECT_NAME=tfs

# Specify all of our different build configs.
matrix:
    # Don't wait for builds that are allowed to fail.
    fast_finish: true

    allow_failures:
        # FIXME(#9): i686-unknown-linux-gnu cross compile is broken
        - env: TARGET=i686-unknown-linux-gnu RUST=stable PKG_CONFIG_ALLOW_CROSS=1
        # FIXME(#13): Cross-compiled fuse not available?
        - env: TARGET=x86_64-unknown-linux-musl RUST=stable PKG_CONFIG_ALLOW_CROSS=1

    # Our actual builds
    include:
        # Cross Compiles:

        # Linux i686-unknown-linux-gnu
        # FIXME(#9): pkg-config doesn't pick up fuse
        - os: linux
          dist: trusty
          env: TARGET=i686-unknown-linux-gnu RUST=stable PKG_CONFIG_ALLOW_CROSS=1
          rust: stable # Only cross-compile from stable
          install:
              - "sudo dpkg --add-architecture i386"
              - "sudo apt-get update || true" # This might fail but we don't care
              - "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libfuse-dev:i386"
              - "bash ci/install.sh"
          addons:
            apt:
              packages:
                # Cross compiler and cross compiled C libraries
                - gcc-multilib

        # OS X i686-apple-darwin
        - os: osx
          osx_image: osx10.11
          env: TARGET=i686-apple-darwin RUST=stable PKG_CONFIG_ALLOW_CROSS=1
          rust: stable # Only cross-compile from stable

        # Linux x86_64-unknown-linux-musl
        # FIXME(#13): Cross-compiled fuse not available?
        - os: linux
          dist: trusty
          env: TARGET=x86_64-unknown-linux-musl RUST=stable PKG_CONFIG_ALLOW_CROSS=1
          rust: stable
          addons:
            apt:
              packages:
                - libfuse-dev

        # Native compiles:

        # Linux x86_64-unknown-linux-gnu
        - os: linux
          dist: trusty
          env: TARGET=x86_64-unknown-linux-gnu RUST=stable
          rust: stable
          addons:
            apt:
              packages:
                - libfuse-dev
        - os: linux
          dist: trusty
          env: TARGET=x86_64-unknown-linux-gnu
          rust: beta
          addons:
            apt:
              packages:
                - libfuse-dev
        - os: linux
          dist: trusty
          env: TARGET=x86_64-unknown-linux-gnu
          rust: nightly
          addons:
            apt:
              packages:
                - libfuse-dev

        # OS X x86_64-apple-darwin
        - os: osx
          osx_image: osx10.11
          rust: stable
          env: TARGET=x86_64-apple-darwin RUST=stable
        - os: osx
          osx_image: osx10.11
          rust: beta
          env: TARGET=x86_64-apple-darwin
        - os: osx
          osx_image: osx10.11
          rust: nightly
          env: TARGET=x86_64-apple-darwin


install:
    - bash ci/install.sh

before_deploy:
    - bash ci/before_deploy.sh

script:
    - bash ci/script.sh

deploy:
    provider: releases
    api_key:
        secure: "Dna9tLlMfvZdENbpUvFOpCjvFlW+zdFou9bgk+tfRhTXVVpTLSCfSIM7iPj8wGY5uSniq8Lnb1eYzD6orbqm89IcvlganFFM5n1+Ge/czQgaRwBsAD4KuDps5E77TWe+TV7Vv/MmeiNH+hFz5JtskGAnEc5xgRyqEfHbzwFSsZtOM+Auc0RrDlEWMuV7ahLxrMeKIYrWL3YDd0bwBbCGV6s+35X3FO653T7Eocfvfd8yFj5l20fgfpZHQ3uRwUcVNNnxDrgZ080uPBxfOf80jMRS/zM0JtyMUcmkZX+hVkoU7Cn60vAFRJwGex0bvDthwFevZEYV4j0j7QzjlYC16MprX/1uUgojMUvW4a88nx5KgXUoglEtgTFhV2vGdemWmzx67j6+fcv3sCT7T+b8W755wk2qougp6Byk5xJAbN5WnRFlqmhsMsGwK403WsLrpsEOg/UZ0uc03Pm8pgM3CLdoJehu1gLltDD4EBYabK7SfNh2hunZFE3zz9LDVy2lbNiNg0qTyjqkOCEq4Yz1sfRmSbxrhj2UjhY5uGbX/Omzq9tUX/BftlHFURX0viGxAd0z9LZsSm/Kuz+DEaL2TQO1+VAdRP84MvqyIqECNesxnLIfOcWI0iHTEJM6BCLtNUrtgJ8n8SKsknqtRwbV+/+4q1aoSZuSEwpfS7wTMIo="
    file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
    skip_cleanup: true
    on:
        repo: terminalcloud/tfs # Prevent failed deploys on forks
        condition: $RUST = stable
        branch: master
        tags: true

